<a href="https://colab.research.google.com/github/shreshthasharma110/PANDAS_LEARNING/blob/main/05_filtering_sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/sample_data/california_housing_train.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [3]:
df["median_income"]

0        1.4936
1        1.8200
2        1.6509
3        3.1917
4        1.9250
          ...
16995    2.3571
16996    2.5179
16997    3.0313
16998    1.9797
16999    3.0147
Name: median_income, Length: 17000, dtype: float64

In [4]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [5]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [6]:
df.iloc[10]

longitude              -114.6000
latitude                 33.6200
housing_median_age       16.0000
total_rooms            3741.0000
total_bedrooms          801.0000
population             2434.0000
households              824.0000
median_income             2.6797
median_house_value    86500.0000
Name: 10, dtype: float64

filterning row

In [7]:
df[df['median_income']>5]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
32,-115.39,32.76,16.0,1136.0,196.0,481.0,185.0,6.2558,146300.0
69,-115.55,32.98,33.0,2266.0,365.0,952.0,360.0,5.4349,143000.0
92,-115.57,32.78,20.0,1534.0,235.0,871.0,222.0,6.2715,97200.0
98,-115.58,32.78,5.0,2494.0,414.0,1416.0,421.0,5.7843,110100.0
100,-115.59,32.79,8.0,2183.0,307.0,1000.0,287.0,6.3814,159900.0
...,...,...,...,...,...,...,...,...,...
16737,-122.89,38.38,16.0,2017.0,369.0,931.0,336.0,5.7664,267500.0
16762,-122.94,38.57,33.0,1530.0,266.0,728.0,250.0,5.1005,266700.0
16776,-123.00,38.33,8.0,3223.0,637.0,851.0,418.0,5.6445,364800.0
16802,-123.17,39.18,14.0,2240.0,327.0,1030.0,308.0,5.9585,214900.0
16899,-124.05,40.94,14.0,1452.0,217.0,516.0,181.0,5.0329,165600.0

multiple condition

In [8]:
df[(df["median_income"] > 5) & (df["housing_median_age"] > 20)]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
69,-115.55,32.98,33.0,2266.0,365.0,952.0,360.0,5.4349,143000.0
260,-116.55,33.84,28.0,2992.0,562.0,676.0,346.0,5.7613,500001.0
352,-116.90,32.79,21.0,3770.0,491.0,1410.0,446.0,6.7685,294700.0
363,-116.91,32.81,22.0,4331.0,637.0,1952.0,654.0,5.4834,232000.0
364,-116.91,32.80,32.0,1943.0,287.0,1081.0,292.0,5.6846,208800.0
...,...,...,...,...,...,...,...,...,...
16580,-122.70,38.46,29.0,2891.0,459.0,1012.0,441.0,5.0415,240200.0
16620,-122.72,38.48,23.0,2296.0,356.0,902.0,334.0,6.0298,289100.0
16664,-122.76,38.35,30.0,2260.0,374.0,958.0,359.0,5.0323,222400.0
16735,-122.89,38.42,28.0,2388.0,437.0,1015.0,381.0,5.1512,268300.0
16762,-122.94,38.57,33.0,1530.0,266.0,728.0,250.0,5.1005,266700.0

sorting values

In [9]:
df.sort_values("median_income")

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
6631,-118.28,33.93,52.0,117.0,33.0,74.0,45.0,0.4999,90600.0
11130,-121.01,37.65,52.0,178.0,53.0,152.0,62.0,0.4999,82500.0
10260,-119.99,36.09,23.0,333.0,92.0,198.0,55.0,0.4999,100000.0
15369,-122.29,37.81,46.0,12.0,4.0,18.0,7.0,0.4999,67500.0
2888,-117.75,34.06,52.0,62.0,9.0,44.0,16.0,0.4999,112500.0
...,...,...,...,...,...,...,...,...,...
7880,-118.40,34.10,27.0,3979.0,510.0,1351.0,520.0,15.0001,500001.0
14883,-122.22,37.44,32.0,4281.0,501.0,1318.0,484.0,15.0001,500001.0
15642,-122.36,37.56,32.0,4684.0,540.0,1512.0,511.0,15.0001,500001.0
14884,-122.22,37.40,32.0,2297.0,287.0,814.0,283.0,15.0001,500001.0
4461,-118.04,34.13,35.0,249.0,31.0,268.0,29.0,15.0001,500001.0